package com.boot.mapper;

import java.util.List;
import java.util.Map;

import com.boot.entity.Foods;

public interface FoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Thu May 03 20:24:11 CST 2018
     */
    int deleteByPrimaryKey(Integer foodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Thu May 03 20:24:11 CST 2018
     */
    int insert(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Thu May 03 20:24:11 CST 2018
     */
    int insertSelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Thu May 03 20:24:11 CST 2018
     */
    Foods selectByPrimaryKey(Integer foodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Thu May 03 20:24:11 CST 2018
     */
    int updateByPrimaryKeySelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Thu May 03 20:24:11 CST 2018
     */
    int updateByPrimaryKey(Foods record);

	List<Foods> selectFoodList(Map<String, Object> map);

	Integer selectFoodsCount(Foods foods);
}